$("#USSR").click(function(){
    $("#AK47").attr("src","https://www.samgerrans.com/wp-content/uploads/2013/03/communism-300x188.png");
});
$("#capitalist").click(function(){
    $("#AK47").attr("src","https://pics.me.me/die-capitalist-scum-comrade-link-knows-what-to-do-28274938.png");
});
$("#bigBOOm").click(function(){
    $("#bigBOOm").slideDown();
});
$("#Katyusha").hover(function(){
    $("#Katyusha").fadeOut();
});
$("#Katyusha").click(function(){
    $("Katyusha").fadeIn();
});
